# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cd54704d4af0225dc0f2217509d61a6a4cd69b91c14ad487af593448a8123e1098b455c3261264f9a9a0e18dbb127c7d36eac2edc8a268fb0b76806ea61e43be

test:
  secret_key_base: fa74140db1da5b1f0a2d3cbe54ac35d2eb3b22493d4f905f606c89a96c8dd187b765efaa74e089b6fba9f88c317f73f5f9ecd338622a7a651b335aa52c696391

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
